### ISSUE TITLE
game crashed as soon as friend left a rat merchant.

### ISSUE THREAD

**Issue by JohnKirklandChalk** [Tempus/Slay-the-Spire-Together#15]
Also, my screen didn't show any of the rat merchant symbols. If i host a game and my friend joins it crashes as soon as i make a neow choice.

java.lang.IndexOutOfBoundsException: Index: 15, Size: 15
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_144]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_144]
	at chronoMods.steam.NetworkHelper.parseData(NetworkHelper.java:468) ~[Spire%20with%20Friends.jar:?]
	at chronoMods.steam.NetworkHelper.update(NetworkHelper.java:106) ~[Spire%20with%20Friends.jar:?]
	at chronoMods.steam.NetworkHelper$SteamUpdate.Postfix(NetworkHelper.java:86) ~[Spire%20with%20Friends.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:900) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:419) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Comment by Tempus** [comment]
Double check your versions, this is almost certainly the 1.3 and 1.4
version crash. Sorry!

On March 19, 2021 at 5:14:01 AM, JohnKirklandChalk ***@***.***)
wrote:

Also, my screen didn't show any of the rat merchant symbols. If i host a
game and my friend joins it crashes as soon as i make a neow choice.

java.lang.IndexOutOfBoundsException: Index: 15, Size: 15
at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_144]
at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_144]
at chronoMods.steam.NetworkHelper.parseData(NetworkHelper.java:468)
~[Spire%20with%20Friends.jar:?]
at chronoMods.steam.NetworkHelper.update(NetworkHelper.java:106)
~[Spire%20with%20Friends.jar:?]
at
chronoMods.steam.NetworkHelper$SteamUpdate.Postfix(NetworkHelper.java:86)
~[Spire%20with%20Friends.jar:?]
at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:900)
~[?:?]
at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:419)
[?:?]
at
com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
[?:?]
at
com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
[desktop-1.0.jar:?]

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Tempus/Slay-the-Spire-Together/issues/15>, or
unsubscribe
