### ISSUE TITLE
spire with frienmds :mod bug

### ISSUE THREAD

**Issue by JX190809** [Tempus/Slay-the-Spire-Together#18]
15:50:47.657 INFO dungeons.AbstractDungeon> Game Seed: -3456381063140186460
15:50:47.657 INFO dungeons.AbstractDungeon> Map generation time: 13ms
15:50:50.667 INFO audio.MainMusic> Disposing MainMusic: MENU
15:50:58.487 INFO neow.NeowEvent> Disposing Neow asset.
15:50:58.488 INFO core.CardCrawlGame> Exception occurred in CardCrawlGame render method!
15:50:58.488 ERROR core.CardCrawlGame> Exception caught
java.util.IllegalFormatConversionException: d != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302) ~[?:1.8.0_144]
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793) ~[?:1.8.0_144]
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747) ~[?:1.8.0_144]
	at java.util.Formatter.format(Formatter.java:2520) ~[?:1.8.0_144]
	at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_144]
	at java.lang.String.format(String.java:2940) ~[?:1.8.0_144]
	at com.megacrit.cardcrawl.integrations.steam.SteamIntegration.setRichPresenceDisplayPlaying(SteamIntegration.java:51) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2278) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2119) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.updateFading(AbstractDungeon.java:2848) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2517) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:871) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:419) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
15:50:58.496 INFO core.CardCrawlGame> PAUSE()
15:50:58.502 INFO core.CardCrawlGame> Game shutting down...
15:50:58.503 INFO core.CardCrawlGame> Flushing saves to disk...
15:50:58.610 INFO helpers.File> Failed to validate source=E:\steam\steamapps\common\SlayTheSpire\preferences\STSDataWatcher, retrying...
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202) ~[?:1.8.0_144]
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216) ~[?:1.8.0_144]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[?:1.8.0_144]
	at java.nio.channels.Channels.writeFully(Channels.java:101) ~[?:1.8.0_144]
	at java.nio.channels.Channels.access$000(Channels.java:61) ~[?:1.8.0_144]
	at java.nio.channels.Channels$1.write(Channels.java:174) ~[?:1.8.0_144]
	at java.nio.file.Files.write(Files.java:3297) ~[?:1.8.0_144]
	at com.megacrit.cardcrawl.helpers.File.writeAndValidate(File.java:155) [desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.helpers.File.save(File.java:63) [desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.helpers.FileSaver.consume(FileSaver.java:42) [desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.helpers.FileSaver.run(FileSaver.java:25) [desktop-1.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
15:50:58.611 INFO core.CardCrawlGame> Shutting down publisher integrations...
15:50:58.611 INFO helpers.File> java.lang.InterruptedException: sleep interrupted
15:50:58.614 INFO core.CardCrawlGame> Flushing logs to disk. Clean shutdown successful.
Game closed.

**Comment by Tempus** [comment]
This is a Chinese language bug. Fixed in 1.5
