### ISSUE TITLE
crash on start of in-game run

### ISSUE THREAD

**Issue by yfyldfylfhkcvkyd** [Tempus/Slay-the-Spire-Together#66]
Cause:
java.lang.IndexOutOfBoundsException: Index: 9, Size: 4
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at chronoMods.network.NetworkHelper.parseData(NetworkHelper.java:161)
	at chronoMods.network.NetworkHelper.update(NetworkHelper.java:120)
	at chronoMods.network.NetworkHelper$SteamUpdate.Postfix(NetworkHelper.java:105)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:906)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by crecerhecer** [comment]
then i playing solo its doesn't crash
